name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches:
      - main   # เมื่อ push มาที่ main branch ของ repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo ต้นทาง (สมมติคุณเอาไฟล์ไว้ในโฟลเดอร์ source/)
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: source

      # 2️⃣ Copy static files (ถ้าอยู่ใน source/)
      - name: Copy static files
        run: |
          mkdir -p site
          cp -r source/* site/

      # 3️⃣ Deploy ไป GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site       # โฟลเดอร์ที่ต้องการ deploy
          publish_branch: main      # branch ที่ GitHub Pages ใช้
